version: '3'

services:
  web.client:
    build:
      dockerfile: ./web.client/Dockerfile
      context: .
    image: home-automation-web-client
    volumes:
      - ./web.client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:8080

  service.registry.device:
    build:
      dockerfile: ./service.registry.device/Dockerfile
      context: .
    image: home-automation-device-registry
    volumes:
      - ./service.registry.device:/usr/src/app
      - ./libraries/python:/root/.local/lib/python3.5/site-packages
    ports:
      - 5001:5001
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py

  service.event-bus:
    build:
      dockerfile: ./service.event-bus/dev.dockerfile
      context: .
    image: home-automation-service-event-bus
    volumes:
      - ./service.event-bus:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5004:80
    environment:
      NODE_ENV: development

  service.api-gateway:
    image: jakewright/drawbridge
    volumes:
      - ./service.api-gateway/config.dev.yaml:/config/config.yaml
    ports:
      - 5005:80

  service.controller.dmx:
    build:
      dockerfile: ./service.controller.dmx/Dockerfile
      context: .
    image: home-automation-controller-dmx
    volumes:
      - ./service.controller.dmx:/usr/src/app
      - ./libraries/python:/root/.local/lib/python2.7/site-packages
    ports:
      - 5006:5006
      - 9090:9090
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py

  service.controller.hue:
    build:
      dockerfile: ./service.controller.hue/dev.dockerfile
      context: .
    image: home-automation-controller-hue
    volumes:
      - ./service.controller.hue:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 5007:5007
    environment:
      NODE_ENV: development

  redis:
    image: redis:latest
    ports:
      - 6379:6379
