version: '3'

services:
  service.registry.device:
    build:
      dockerfile: ./service.registry.device/Dockerfile
      context: .
    image: home-automation-device-registry
    volumes:
      - ./service.registry.device:/usr/src/app
      - ./libraries/python:/root/.local/lib/python3.5/site-packages
    ports:
      - 5001:5001
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py

