version: '3'

services:
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  filebeat:
    build:
      dockerfile: filebeat/Dockerfile
      context: .
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  logstash:
    build:
      dockerfile: logstash/Dockerfile
      context: .
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./log:/var/log
    ports:
      - 7514:7514 # Syslog
      - 5044:5044 # Beats

  mysql:
    image: mysql:latest
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: home_automation
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  service.api-gateway:
    image: jakewright/drawbridge
    volumes:
      - ./service.api-gateway/config.dev.yaml:/config/config.yaml
    ports:
      - 7005:80

  service.config:
    build:
      dockerfile: ./service.config/dev.dockerfile
      context: .
    image: home-automation-service-config
    volumes:
      - .:/go/src/github.com/jakewright/home-automation
      - ./private/config/dev.yaml:/data/config.yaml
      - /go/src/github.com/jakewright/home-automation/vendor
    ports:
      - 7002:80
    env_file:
      - ./.env

  service.controller.dmx:
    build:
      dockerfile: ./service.controller.dmx/Dockerfile
      context: .
    image: home-automation-controller-dmx
    volumes:
      - ./service.controller.dmx:/usr/src/app
      - ./libraries/python:/root/.local/lib/python2.7/site-packages
    ports:
      - 7006:80
      - 9090:9090
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py
    env_file:
      - ./.env

  service.controller.hue:
    build:
      dockerfile: ./service.controller.hue/dev.dockerfile
      context: .
    image: home-automation-controller-hue
    volumes:
      - ./service.controller.hue:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7007:80
    environment:
      NODE_ENV: development
    env_file:
      - ./.env

  service.controller.infrared:
    build:
      dockerfile: ./service.controller.infrared/dev.dockerfile
      context: .
    image: home-automation-controller-infrared
    volumes:
      - ./service.controller.infrared:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7008:80
    env_file:
      - ./.env

  service.controller.plug:
    build:
      dockerfile: service.controller.plug/dev.dockerfile
      context: .
    image: home-automation-controller-plug
    volumes:
      - ./service.controller.plug:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7009:80
    environment:
      NODE_ENV: development
    env_file:
      - ./.env

  service.device-registry:
    build:
      dockerfile: service.device-registry/dev.dockerfile
      context: .
    image: home-automation-device-registry
    volumes:
      - .:/go/src/github.com/jakewright/home-automation
      - /go/src/github.com/jakewright/home-automation/vendor
    ports:
      - 7001:80
    env_file:
      - ./.env

  service.event-bus:
    build:
      dockerfile: ./service.event-bus/dev.dockerfile
      context: .
    image: home-automation-service-event-bus
    volumes:
      - ./service.event-bus:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7004:80
    environment:
      NODE_ENV: development
    env_file:
      - ./.env

  service.log:
    build:
      dockerfile: service.log/dev.dockerfile
      context: .
    image: home-automation-log
    volumes:
      - .:/go/src/github.com/jakewright/home-automation
      - ./log/:/var/log:ro
      - /go/src/github.com/jakewright/home-automation/vendor
    ports:
      - 7020:80
    env_file:
      - ./.env

  service.scene:
    build:
        dockerfile: service.scene/dev.dockerfile
        context: .
    image: home-automation-scene
    volumes:
      - .:/app
    ports:
      - 7010:80
    env_file:
      - ./.env

  service.user:
    build:
        dockerfile: service.user/dev.dockerfile
        context: .
    image: home-automation-user
    volumes:
      - .:/app
    ports:
      - 7011:80
    env_file:
      - ./.env

  web.client:
    build:
      dockerfile: ./web.client/dev.dockerfile
      context: .
    image: home-automation-web-client
    volumes:
      - ./web.client:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7000:8080
    env_file:
      - ./.env
