version: '3'

services:
  web.client:
    build:
      dockerfile: ./web.client/dev.dockerfile
      context: .
    image: home-automation-web-client
    volumes:
      - ./web.client:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7000:8080
    env_file:
     - ./.env

  service.registry.device:
    build:
      dockerfile: ./service.registry.device/dev.dockerfile
      context: .
    image: home-automation-service-device-registry
    volumes:
      - ./service.registry.device:/usr/src/app
      - ./libraries/python:/root/.local/lib/python3.5/site-packages
    ports:
      - 7001:80
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py
    env_file:
     - ./.env

  service.config:
    build:
      dockerfile: ./service.config/dev.dockerfile
      context: .
    image: home-automation-service-config
    volumes:
      - .:/go/src/home-automation
      - ./service.config/data/dev.yaml:/data/config.yaml
    ports:
     - 7002:80
    env_file:
     - ./.env

  service.event-bus:
    build:
      dockerfile: ./service.event-bus/dev.dockerfile
      context: .
    image: home-automation-service-event-bus
    volumes:
      - ./service.event-bus:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7004:80
    environment:
      NODE_ENV: development
    env_file:
     - ./.env

  service.api-gateway:
    image: jakewright/drawbridge
    volumes:
      - ./service.api-gateway/config.dev.yaml:/config/config.yaml
    ports:
      - 7005:80
    env_file:
     - ./.env

  service.controller.dmx:
    build:
      dockerfile: ./service.controller.dmx/Dockerfile
      context: .
    image: home-automation-controller-dmx
    volumes:
      - ./service.controller.dmx:/usr/src/app
      - ./libraries/python:/root/.local/lib/python2.7/site-packages
    ports:
      - 7006:80
      - 9090:9090
    environment:
      APP_CONFIG_FILE: /usr/src/app/config/development.py
    env_file:
     - ./.env

  service.controller.hue:
    build:
      dockerfile: ./service.controller.hue/dev.dockerfile
      context: .
    image: home-automation-controller-hue
    volumes:
      - ./service.controller.hue:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7007:80
    environment:
      NODE_ENV: development
    env_file:
     - ./.env

  service.controller.infrared:
    build:
      dockerfile: ./service.controller.infrared/dev.dockerfile
      context: .
    image: home-automation-controller-infrared
    volumes:
      - .:/go/src/home-automation
    ports:
      - 7008:80
    env_file:
      - ./.env

  service.controller.plug:
    build:
      dockerfile: service.controller.plug/dev.dockerfile
      context: .
    image: home-automation-controller-plug
    volumes:
      - ./service.controller.plug:/usr/src/app
      - /usr/src/app/node_modules
      - ./libraries/javascript:/usr/src/libraries/javascript
      - /usr/src/libraries/javascript/node_modules
    ports:
      - 7009:80
    environment:
      NODE_ENV: development
    env_file:
      - ./.env

  service.log:
    build:
      dockerfile: service.log/dev.dockerfile
      context: .
    image: home-automation-log
    volumes:
      - .:/go/src/home-automation
      - ./log/:/var/log:ro
    ports:
      - 7020:80
    env_file:
      - ./.env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
     - ./.env

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.0.0
    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7514:7514
    environment:
      - "strict.perms:false"
    user: root
