apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "service-name" .}}
  labels:
    app: {{template "service-name" .}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{template "service-name" .}}
  template:
    metadata:
      labels:
        app: {{template "service-name" .}}
    spec:
      containers:
        - name: {{template "service-name" .}}
          image: {{.Values.image}}
          imagePullPolicy: {{.Values.pullPolicy}}
          ports:
            - containerPort: {{.Values.containerPort}}
          env:
            {{- range $key, $value := .Values.config }}
            - name: {{$key}}
              value: {{$value | quote}}
            {{- end }}
