apiVersion: v1
kind: Service
metadata:
  name: {{template "service-name" .}}
  labels:
    app: {{template "service-name" .}}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    app: {{template "service-name" .}}
