apis:
  service.config:
    name: Config Service
    prefix: service.config
    upstream_url: http://192.168.1.100:7002
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.registry.device:
    name: Device Registry
    prefix: service.registry.device
    upstream_url: http://192.168.1.100:7001
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.dmx:
    name: DMX Controller
    prefix: service.controller.dmx
    upstream_url: http://192.168.1.213:7006
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.hue:
    name: Hue Controller
    prefix: service.controller.hue
    upstream_url: http://192.168.1.100:7007
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.infrared:
    name: Infrared Controller
    prefix: service.controller.infrared
    upstream_url: http://192.168.1.100:7008
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3

  service.controller.plug:
    name: TP-Link Plug Controller
    prefix: service.controller.plug
    upstream_url: http://192.168.1.100:7009
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 3
