apis:
  service.registry.device:
    name: Device Registry
    prefix: service.registry.device
    upstream_url: http://service.registry.device
    allow_cross_origin: true

  service.controller.dmx:
    name: DMX Controller
    prefix: service.controller.dmx
    upstream_url: http://service.controller.dmx
    allow_cross_origin: true
