apis:
  service.config:
    name: Config Service
    prefix: service.config
    upstream_url: http://service.config
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.registry.device:
    name: Device Registry
    prefix: service.registry.device
    upstream_url: http://service.registry.device
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.dmx:
    name: DMX Controller
    prefix: service.controller.dmx
    upstream_url: http://service.controller.dmx
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.hue:
    name: Hue Controller
    prefix: service.controller.hue
    upstream_url: http://service.controller.hue
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.infrared:
    name: Infrared Controller
    prefix: service.controller.infrared
    upstream_url: http://service.controller.infrared
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1

  service.controller.plug:
    name: TP-Link Plug Controller
    prefix: service.controller.plug
    upstream_url: http://service.controller.plug
    allow_cross_origin: true
    plugins:
      - name: retry
        enabled: true
        config:
          attempts: 1
