apis:
  service.config:
    name: Config Service
    prefix: service.config
    upstream_url: http://192.168.1.100:7002
    allow_cross_origin: true

  service.registry.device:
    name: Device Registry
    prefix: service.registry.device
    upstream_url: http://192.168.1.100:7001
    allow_cross_origin: true

  service.controller.dmx:
    name: DMX Controller
    prefix: service.controller.dmx
    upstream_url: http://192.168.1.213:7006
    allow_cross_origin: true

  service.controller.hue:
    name: Hue Controller
    prefix: service.controller.hue
    upstream_url: http://192.168.1.100:7007
    allow_cross_origin: true
