name: Go
on: [push]
jobs:

  lint:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: go get -v -t -d ./...
      
    - name: goimports
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        printf "$PATH\n"
        go get -u golang.org/x/tools/cmd/goimports
        test -z "$(goimports -l .)"
    
    - name: go vet
      run: go vet ./...
      
    - name: golint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        printf "$PATH\n"
        go get -u golang.org/x/lint/golint    
        golint -set_exit_status ./...

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Run unit tests
      run: go test ./...
